- name: verify win_command module
  hosts: all
  tasks:
    - name: run ipconfig and return result
      win_command: ipconfig
      register: ipconfig
    - debug: var=ipconfig
    - name: run echo computername
      win_command: echo %computername%
      register: computername
    - debug: var=computername
