- name: verify win_command module
  hosts: all
  gather_facts: no
  vars:
    test: ['192','168','14','21']
#
  tasks:
#  
    - debug:
      msg: "{{ test | join('.') }}"
#
    - name: Read from file
      slurp:
        src: c:\temp\users.txt
        register: users
    - debug:
        msg: "{{ users['content'] | b64decode }}"
#
    - name: Download file from URL
      win_get_url:
        url: https://github.com/imanol-RL/win_cmds/blob/master/cmd_ipconfig.yml
        dest: C:\Temp\cmd_ipconfig.yml
#
    - name: Download file from URL
      win_get_url:
        url: https://github.com/imanol-RL/win_cmds/cmd_ipconfig.yml
        dest: C:\Temp\cmd_ipconfig.yml
#
    - name: run ipconfig and return result
      win_command: ipconfig
      register: ipconfig
    - debug: var=ipconfig
#
    - name: Get hostname
      win_command: cmd.exe /c echo %computername%
      register: my_hostname
    - debug: var=my_hostname
#    
#    - name: view facts
#    - debug: var=vars
#    - debug: var=hostvars[inventory_hostname]
#      - setup:
#        register: ansible_facts
#      - debug: item
#        with_dict: ansible_facts
