- name: verify win_command module
  hosts: all
  gather_facts: yes
  tasks:
    - name: run ipconfig and return result
      win_command: ipconfig
      register: ipconfig
    - debug: var=ipconfig
#
    - name: Get hostname
      win_command: cmd.exe /c echo %computername%
      register: my_hostname
    - debug: var=my_hostname
#    
#    - name: view facts
#    - debug: var=vars
#    - debug: var=hostvars[inventory_hostname]
#      - setup:
#        register: ansible_facts
#      - debug: item
#        with_dict: ansible_facts
