- name: Read Remote File and debug
  hosts: all
  gather_facts: no
  tasks:
  - name: Read Remote File
    slurp:
      src: C:\Temp\#Ansible\Read_from_Ansible.txt
    register: remote_file

  - debug:
      msg: "{{ remote_file['content'] | b64decode }}"

#ok: [192.168.122.24] => {
#    "msg": "User01,Description01,Pwd01\r\nUser02,Description02,Pwd02\r\nUser03,Description03,Pwd03"
#}

  - debug:
      msg: "{{ remote_file['content'] | b64decode | regex_findall('\r\n') | first }}"

