# win_user_create_with_parameters.yml
- name: Query if user exist and read properties
  hosts: all
  gather_facts: yes
  tasks:
#
  - name: create user
    win_user:
      name: "{{ var_username }}"
      account_disabled: no
      account_locked: no
      description: "{{ansible_date_time.date}} {{ var_description }}"
      fullname: "{{ var_fullname }}"
      password: "{{ var_pwd }}"
      password_expired: no
      password_never_expires: no
      state: present
      groups:
        - "{{ var_group }}"
#        - Users
  - name: "{{ansible_date_time.date}}" - Query if user "{{ var_username }}" exist
    win_user:
      name: "{{ var_username }}"
      state: query
#
#Example:
#var_username: imanol_01
#var_description: created with Ansible
#var_fullname: Imanol 01 created with Ansible
#var_pwd: pwddesde.awx.
#var_group: Administrators
# (Administrators / Users)
