# win_user_verify.yml
- name: Query if user exist and read properties
  hosts: all
  gather_facts: no
  tasks:
  - name: Query if user exist
    win_user:
      name: IMANOL.RAMIREZ
      state: query
#
  - name: create user
    win_user:
      name: "{{ var_username }}"
      account_disabled: no
      account_locked: no
      description: "{{ var_description }}"
      fullname: 'IBM Imanol'
      password: 'quincecaracters'
      password_expired: no
      password_never_expires: no
      state: present
      groups:
        - Administrators
        - Users
#
# 
