- name: download files from URL
  hosts: all
  gather_facts: no
  tasks:
    - name: Download file 1 from URL (win_file_DownloadFromUrl.yml)
      win_get_url:
        url: https://github.com/imanol-RL/win_cmds/blob/master/win_file_DownloadFromUrl.yml
        dest: C:\Temp\win_file_DownloadFromUrl.yml
        force: yes
#
    - name: Download file 2 from URL
      win_get_url:
        url: https://github.com/imanol-RL/win_cmds/blob/master/users.txt
        dest: C:\Temp\users.txt
        force: yes
#
